import { Inter } from 'next/font/google'
import { Chakra } from '@/contexts/ChakraProvider'
import { fonts } from '@/lib/fonts'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={fonts.rubik.variable}>
      <body className={inter.className}>
        <Chakra>{children}</Chakra>
      </body>
    </html>
  )
}
